### ISSUE TITLE
Switch from azure pipelines to github actions

### ISSUE THREAD

**Issue by ChrisJefferson** [minion/minion#12]
There is no particular reason we are using azure pipelines, and github actions integrates better with github

**Comment by ozgurakgun** [comment]
@lixitrixi will look into this

**Comment by ChrisJefferson** [comment]
Thanks!

I've just added some more tests (which is what made me think this needed doing), it's in the "no-leaks" branch (which I'll merge assuming it passes).

Basically, I think the tests are in 2 groups:

1) Some basic tests that should be run on Mac and Linux.
2) Tests (the two which have the word 'valgrind' mentioned), that should only run on Linux. Also they take longer, but hopefully not too long.

I'd also like to bring back windows tests, but firstly we can get the others working. The main problem with windows is making sure a working compiler + python + make is installed.

**Comment by ChrisJefferson** [comment]
Just to say, I merged 'no-leaks' into the master branch.

I should also get around to renaming master to main sometime.
