### ISSUE TITLE
libminion: SIGCLD handling in parallel minion breaks Rust threading.

### ISSUE THREAD

**Issue by niklasdewally** [minion/minion#25]
In [a recent minion_rs PR](https://github.com/conjure-cp/conjure-oxide/pull/219) I encountered a bug where `cargo test` threads / sub-processes spawned using `Command::new()` would randomly fail with `ECHILD` errors or segfault.

This seems to be due to this line in Minion's parallel constructor: 

```cpp
  signal(SIGCHLD, SIG_IGN);
```
(https://github.com/minion/minion/blob/main/minion/parallel.cpp#L91)

While this is useful for preventing zombie children when running Minion as a standalone program, it does not work over FFI. This is because Rust's standard library uses information generated in the handling of SIGCHILD to get information about a child when it exits. 

Although this is parallel Minion code, and `minion_rs` does not support parallel Minion, an instance of Parallel is needed nonetheless during search to do timekeeping etc, so this is always called.

**Proposed solution**

The quick fix solution I used was to surround this signal override with `#ifndefine LIBMINION`, disabling this behaviour for library usage. This fixed the errors in my PR and did not break any existing tests.

---

I am not sure what the intended behaviour of this is and how disabling this impacts Minion. My assumption is that it would make the little multi-processing used in non-parallel Minion more memory intensive but would not ultimately matter; however, I do not understand Minion internals or concurrency well enough to know for sure that I haven't broken anything. 

Any advice on this would be greatly appreciated :)

**Comment by ChrisJefferson** [comment]
I'm moving the signal handling to when we actually call 'fork' (which is when we really need it) -- the 'fork' is probably never going to work well with rust, as we would also fork the whole attached Rust program.

**Comment by ChrisJefferson** [comment]
The (hoped for) fix is in #26 .

There is still one other issue -- minion grabs the 'ctrl+c' handler too -- this code should possibly also be disabled, but at least the problems won't be so immediately severe.

**Comment by niklasdewally** [comment]
Thank you for this fix; I'll give it a test today and let you know if that fixes everything :)

I've been told about other occasional segfaults on intel Macs using minion_rs, so there may be more questions on the way. I imagine it's a bug in my Rust concurrency code though :)

**Comment by niklasdewally** [comment]
This fixed the issue; thanks :)
